### ISSUE TITLE
WARNING: Cannot locate native library: macosx/liblwjgl.dylib

### ISSUE THREAD

**Issue by maacl** [ztellman/penumbra#41]
When trying to use penumbra directly as described here https://github.com/ztellman/penumbra/wiki/getting-started#using-penumbra-directly I get the following:

user=> (require 'examples)
Oct 18, 2013 1:18:50 AM penumbra.Natives extractNativeLibs
INFO: Extraction Directory #1: file:/Users/mac/Downloads/penumbra/src/penumbra/
Oct 18, 2013 1:18:50 AM penumbra.Natives extractNativeLibs
INFO: Extraction Directory #2: /Users/mac/Downloads/penumbra
Oct 18, 2013 1:18:50 AM penumbra.Natives extractNativeLibs
INFO: Extraction Directory #3: /Users/mac/Downloads/penumbra
Oct 18, 2013 1:18:50 AM penumbra.Natives extractNativeLib
WARNING: Cannot locate native library: macosx/liblwjgl.dylib
nil
user=> (examples/run)
JavaVM WARNING: JAWT_GetAWT must be called after loading a JVM
org.lwjgl.LWJGLException: Could not get the JAWT interface
	at org.lwjgl.opengl.AWTSurfaceLock.lockAndInitHandle(Native Method)
	at org.lwjgl.opengl.AWTSurfaceLock.access$100(AWTSurfaceLock.java:49)
	at org.lwjgl.opengl.AWTSurfaceLock$1.run(AWTSurfaceLock.java:89)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.lwjgl.opengl.AWTSurfaceLock.privilegedLockAndInitHandle(AWTSurfaceLock.java:86)
	at org.lwjgl.opengl.AWTSurfaceLock.lockAndGetHandle(AWTSurfaceLock.java:64)
	at org.lwjgl.opengl.MacOSXCanvasPeerInfo.initHandle(MacOSXCanvasPeerInfo.java:53)
	at org.lwjgl.opengl.MacOSXDisplayPeerInfo.doLockAndInitHandle(MacOSXDisplayPeerInfo.java:56)
	at org.lwjgl.opengl.PeerInfo.lockAndGetHandle(PeerInfo.java:85)
	at org.lwjgl.opengl.MacOSXContextImplementation.create(MacOSXContextImplementation.java:47)
	at org.lwjgl.opengl.Context.<init>(Context.java:127)
	at org.lwjgl.opengl.Display.create(Display.java:857)
	at org.lwjgl.opengl.Display.create(Display.java:783)
	at penumbra.app.window$create_fixed_window$reify__8092.init_BANG_(window.clj:86)
	at penumbra.app.window$eval7902$fn__8062$G__7866__8064.invoke(window.clj:25)
	at penumbra.app.window$eval7902$fn__8062$G__7865__8067.invoke(window.clj:25)
	at clojure.lang.Var.invoke(Var.java:365)
	at penumbra.app$eval8708$fn__8709.invoke(app.clj:103)
	at penumbra.app.window$eval7902$fn__8062$G__7865__8067.invoke(window.clj:25)
	at penumbra.app$eval8802$fn__8809.invoke(app.clj:116)
	at penumbra.app.core$eval7365$fn__7401$G__7356__7406.invoke(core.clj:20)
	at penumbra.app$start_single_thread$fn__8893$fn__8894.invoke(app.clj:292)
	at penumbra.app.loop$basic_loop.invoke(loop.clj:71)
	at penumbra.app$start_single_thread$fn__8893.invoke(app.clj:296)
	at penumbra.app$start_single_thread.invoke(app.clj:287)
	at penumbra.app$start.invoke(app.clj:318)
	at example.opengl.gears$start.invoke(gears.clj:128)
	at examples$fn__10703$fn__10704.invoke(examples.clj:40)
	at examples$fn__10703.invoke(examples.clj:39)
	at clojure.test$test_var$fn__6131.invoke(test.clj:688)
	at clojure.test$test_var.invoke(test.clj:688)
	at examples$run.invoke(examples.clj:30)
	at user$eval10730.invoke(NO_SOURCE_FILE:1)
	at clojure.lang.Compiler.eval(Compiler.java:5424)
	at clojure.lang.Compiler.eval(Compiler.java:5391)
	at clojure.core$eval.invoke(core.clj:2382)
	at clojure.main$repl$read_eval_print__5624.invoke(main.clj:183)
	at clojure.main$repl$fn__5629.invoke(main.clj:204)
	at clojure.main$repl.doInvoke(main.clj:204)
	at clojure.lang.RestFn.invoke(RestFn.java:702)
	at clojure.tools.nrepl.middleware.interruptible_eval$evaluate$fn__543.invoke(interruptible_eval.clj:56)
	at clojure.lang.AFn.applyToHelper(AFn.java:159)
	at clojure.lang.AFn.applyTo(AFn.java:151)
	at clojure.core$apply.invoke(core.clj:540)
	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1502)
	at clojure.lang.RestFn.invoke(RestFn.java:426)
	at clojure.tools.nrepl.middleware.interruptible_eval$evaluate.invoke(interruptible_eval.clj:41)
	at clojure.tools.nrepl.middleware.interruptible_eval$interruptible_eval$fn__584$fn__586.invoke(interruptible_eval.clj:171)
	at clojure.core$comp$fn__3642.invoke(core.clj:1945)
	at clojure.tools.nrepl.middleware.interruptible_eval$run_next$fn__577.invoke(interruptible_eval.clj:138)
	at clojure.lang.AFn.run(AFn.java:24)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:724)
_NSJVMLoadLibrary: NSAddLibrary failed for /libjawt.dylib
JavaVM FATAL: lookup of function JAWT_GetAWT failed. Exit
Exception in thread "Thread-1" java.net.SocketException: The transport's socket appears to have lost its connection to the nREPL server
                                 transport.clj:95 clojure.tools.nrepl.transport/bencode[fn]
                                 transport.clj:95 clojure.tools.nrepl.transport/bencode[fn]
                                 transport.clj:42 clojure.tools.nrepl.transport/fn-transport[fn]
                                    core.clj:1836 clojure.core/binding-conveyor-fn[fn]
                                      AFn.java:18 clojure.lang.AFn.call
                              FutureTask.java:262 java.util.concurrent.FutureTask.run
                     ThreadPoolExecutor.java:1145 java.util.concurrent.ThreadPoolExecutor.runWorker
                      ThreadPoolExecutor.java:615 java.util.concurrent.ThreadPoolExecutor$Worker.run
                                  Thread.java:724 java.lang.Thread.run
Bye for now!

**Comment by jimmyhmiller** [comment]
Has anyone found a fix for this?

**Comment by maacl** [comment]
No
